// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBAbXysnxxvoJHIuWbN1KQSv_41gJyqFnw',
    appId: '1:864594858129:web:0cb05c244e449a0f072f30',
    messagingSenderId: '864594858129',
    projectId: 'kwiatuszki-uwu',
    authDomain: 'kwiatuszki-uwu.firebaseapp.com',
    databaseURL: 'https://kwiatuszki-uwu-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'kwiatuszki-uwu.appspot.com',
    measurementId: 'G-W5DB7T7K9N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC7-96zAZ2ib5SxMOtBSRnLustyXqfE9qg',
    appId: '1:864594858129:android:0b45dd372674d901072f30',
    messagingSenderId: '864594858129',
    projectId: 'kwiatuszki-uwu',
    databaseURL: 'https://kwiatuszki-uwu-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'kwiatuszki-uwu.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCwte0zPFIDKMA49felYh3TyYthobxTVWE',
    appId: '1:864594858129:ios:76939e93678a72b3072f30',
    messagingSenderId: '864594858129',
    projectId: 'kwiatuszki-uwu',
    databaseURL: 'https://kwiatuszki-uwu-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'kwiatuszki-uwu.appspot.com',
    iosBundleId: 'com.example.kwiatuszkiDev',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCwte0zPFIDKMA49felYh3TyYthobxTVWE',
    appId: '1:864594858129:ios:ccf92b459d315d71072f30',
    messagingSenderId: '864594858129',
    projectId: 'kwiatuszki-uwu',
    databaseURL: 'https://kwiatuszki-uwu-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'kwiatuszki-uwu.appspot.com',
    iosBundleId: 'com.example.kwiatuszkiDev.RunnerTests',
  );
}
